### ISSUE TITLE
inject - ?

### ISSUE THREAD

**Issue by semikor** [pebalk/node-red-contrib-mos-ru#1]
Подскажите, пожалуйста!
Что нужно подать на ноду waterGet, чтобы получить цифры с показаниями на выходе ноды waterGet?
Сейчас получается - что подаю на ноду, то и на ее выходе (т.е. подаю true - на выходе true, подаю метку времени - на выходе она же).
Сама нода waterGet на сайте регистрируется и забирает данные (значения выдает внизу в status), но на выходе значений нет.
Спасибо!

**Comment by pebalk** [comment]
Нода отдает все данные в объекте `msg.content` - там содержатся данные не только по текущим показаниям, но и адрес установки, номера счетчиков, даты поверки, показания за последние три месяца.
Таким образом последнее значение первого счетчика будет расположено в `msg.content.counter[0].indications[0].indication`
