### ISSUE TITLE
0.4.0 и NR 2.1.1

### ISSUE THREAD

**Issue by semikor** [pebalk/node-red-contrib-mos-ru#2]
Обновил node-red-contrib-mos-ru до 0.4.0 и одновременно node-red до 2.1.1
и теперь не могу получить данные из mos.ru, а точнее зайти на сайт.
Ноды получения данных выдают "Error" после "Установки куки".
Ничего не менял (кроме обновления), логин/пароль действующие. В чем может быть проблема?

**Comment by pebalk** [comment]
Не могу воспроизвести со своей стороны. Предлагаю очистить куки через следующий код и посмотреть, какая ошибка вываливается через выход ноды stderr -> к нему присоединить ноду debug и включить вывод всех сообщений (complete msg object).

Код для очистки куки для добавления через импорт:

`[{"id":"95c3515a5c5fe2ce","type":"inject","z":"a6042538d9754cf4","name":"","props":[],"repeat":"","crontab":"","once":false,"onceDelay":"3600","topic":"","x":90,"y":40,"wires":[["35d89adae29dcc64"]]},{"id":"35d89adae29dcc64","type":"exec","z":"a6042538d9754cf4","command":"find . -type f -name \"cookies.json\" -exec rm -f {} \\;  && reboot","addpay":"","append":"","useSpawn":"false","timer":"","winHide":false,"oldrc":false,"name":"","x":400,"y":40,"wires":[[],[],[]]}]`

**Comment by semikor** [comment]
После запуска кода очистки можно получить данные, но только 1 раз, во 2ой раз опять ошибка и опять нужно запускать exec. 
В debug с (complete msg object) на выходе ноды stderr - "undefined".
Под самим exec - "error:1".
До обновления хоть работало, пока mos.ru не сбросит пароль, а сбрасывал 1-2 раза в неделю... Запускал каждый день 1 раз в 5 утра на проверку новых показаний воды и эл-ва.

**Comment by pebalk** [comment]
Ошибка локализовалась, исправлена в версии 0.4.1

**Comment by semikor** [comment]
Обновил до 0.4.1, заодно и NR до 2.1.2.
После запуска exec (под ним по прежнему "Error:1") - waterGet пару раз прислал данные и опять "Error", energyGet выдает только "TimeoutError" и "Error". 
В debug с (complete msg object) на выходе ноды stderr - по прежнему "undefined".
В общем - у меня не хочет работать ((

**Comment by pebalk** [comment]
Обновил до 0.4.2 - в настройках нод добавлен чек-бокс на включение/выключение куков.
Timeout срабатывает если подглючивает подключение к сайту, в последней версии удлинил задержку по тайм-ауту до 60сек

**Comment by semikor** [comment]
Обновил до 0.4.2, заодно и NR до 2.1.3 )))
С " Использовать Куки" - "Error", куки выключил - вроде пока работает, как раньше...
